# Generated by Django 2.2.2 on 2019-06-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20190607_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refmaterial',
            name='thingys',
            field=models.ManyToManyField(related_name='ref_material', to='utils.Thingy'),
        ),
    ]
