# Generated by Django 2.2.2 on 2019-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20190607_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refmaterial',
            name='thingys',
        ),
        migrations.AddField(
            model_name='thingy',
            name='ref_materials',
            field=models.ManyToManyField(related_name='ref_materials', to='utils.RefMaterial'),
        ),
    ]
