# Generated by Django 2.2.2 on 2019-06-08 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20190607_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 9, 14, 839077, tzinfo=utc), verbose_name='init date'),
        ),
    ]
