# Generated by Django 2.2.2 on 2019-06-08 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_thing_init_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='init date'),
        ),
    ]
