# Generated by Django 2.2.2 on 2019-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20190608_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmaterial',
            name='filename',
            field=models.CharField(default='01.jpg', max_length=255, verbose_name='filename'),
            preserve_default=False,
        ),
    ]
