# Generated by Django 2.2.2 on 2019-06-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_refmaterial_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmaterial',
            name='thumbnail',
            field=models.CharField(default='thumbnail.jpg', max_length=255, verbose_name='thumbnail'),
            preserve_default=False,
        ),
    ]
