# Generated by Django 2.2.2 on 2019-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_refmaterial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmaterial',
            name='medium',
            field=models.CharField(default='medium.jpg', max_length=255, verbose_name='medium'),
            preserve_default=False,
        ),
    ]
