# Generated by Django 2.2.2 on 2019-06-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('client', models.CharField(max_length=255, verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Thingy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Thing')),
            ],
        ),
        migrations.CreateModel(
            name='RefMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('thingys', models.ManyToManyField(to='utils.Thingy')),
            ],
        ),
    ]
